class MCU:
    CMD_LENGTH = 4
    N_BYTES_DATA = 2
    TIMER_PERIOD_ms = 5
    TIMEPOINT_PER_UPDATE = 25
    DATA_INTERVAL_ms = TIMER_PERIOD_ms*TIMEPOINT_PER_UPDATE
    RECORD_LENGTH_BYTE = 20
    MSG_LENGTH = TIMEPOINT_PER_UPDATE*RECORD_LENGTH_BYTE

SIMULATION = False    

NUMBER_OF_CHANNELS = 8
NUMBER_OF_CHANNELS_DISPLAY = 5
IS_TEMPERATURE_MEASUREMENT = False
