# set QT_API environment variable
import os 
os.environ["QT_API"] = "pyqt5"
import qtpy

# qt libraries
from qtpy.QtCore import *
from qtpy.QtWidgets import *
from qtpy.QtGui import *

from control._def import *

class NavigationWidget(QFrame):
    def __init__(self, navigationController, main=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.navigationController = navigationController
        self.add_components()
        self.setFrameStyle(QFrame.Panel | QFrame.Raised)

    def add_components(self):
        self.label_Xpos = QLabel()
        self.label_Xpos.setNum(0)
        self.label_Xpos.setFrameStyle(QFrame.Panel | QFrame.Sunken)
        self.entry_dX = QDoubleSpinBox()
        self.entry_dX.setMinimum(0) 
        self.entry_dX.setMaximum(80) 
        self.entry_dX.setSingleStep(1)
        self.entry_dX.setValue(0)
        self.entry_vX = QDoubleSpinBox()
        self.entry_vX.setMinimum(0) 
        self.entry_vX.setMaximum(100) 
        self.entry_vX.setSingleStep(1)
        self.entry_vX.setValue(5)
        self.entry_aX = QDoubleSpinBox()
        self.entry_aX.setMinimum(0) 
        self.entry_aX.setMaximum(500) 
        self.entry_aX.setSingleStep(1)
        self.entry_aX.setValue(20)
        self.combo_ustepX = QComboBox()
        self.combo_ustepX.addItem('1')
        self.combo_ustepX.addItem('2')
        self.combo_ustepX.addItem('4')
        self.combo_ustepX.addItem('8')
        self.combo_ustepX.addItem('16')
        self.combo_ustepX.addItem('32')
        self.combo_ustepX.addItem('64')
        self.btn_moveX_forward = QPushButton('Forward')
        self.btn_moveX_forward.setDefault(False)
        self.btn_moveX_backward = QPushButton('Backward')
        self.btn_moveX_backward.setDefault(False)
        self.btn_cycleX = QPushButton('Cycle')
        self.btn_cycleX.setDefault(False)
        
        self.label_Ypos = QLabel()
        self.label_Ypos.setNum(0)
        self.label_Ypos.setFrameStyle(QFrame.Panel | QFrame.Sunken)
        self.entry_dY = QDoubleSpinBox()
        self.entry_dY.setMinimum(0)
        self.entry_dY.setMaximum(80)
        self.entry_dY.setSingleStep(1)
        self.entry_dY.setValue(0)
        self.entry_vY = QDoubleSpinBox()
        self.entry_vY.setMinimum(0) 
        self.entry_vY.setMaximum(100) 
        self.entry_vY.setSingleStep(1)
        self.entry_vY.setValue(5)
        self.entry_aY = QDoubleSpinBox()
        self.entry_aY.setMinimum(0) 
        self.entry_aY.setMaximum(500) 
        self.entry_aY.setSingleStep(1)
        self.entry_aY.setValue(20)
        self.combo_ustepY = QComboBox()
        self.combo_ustepY.addItem('1')
        self.combo_ustepY.addItem('2')
        self.combo_ustepY.addItem('4')
        self.combo_ustepY.addItem('8')
        self.combo_ustepY.addItem('16')
        self.combo_ustepY.addItem('32')
        self.combo_ustepY.addItem('64')
        self.btn_moveY_forward = QPushButton('Forward')
        self.btn_moveY_forward.setDefault(False)
        self.btn_moveY_backward = QPushButton('Backward')
        self.btn_moveY_backward.setDefault(False)
        self.btn_cycleY = QPushButton('Cycle')
        self.btn_cycleY.setDefault(False)

        self.label_Zpos = QLabel()
        self.label_Zpos.setNum(0)
        self.label_Zpos.setFrameStyle(QFrame.Panel | QFrame.Sunken)
        self.entry_dZ = QDoubleSpinBox()
        self.entry_dZ.setMinimum(0) 
        self.entry_dZ.setMaximum(80) 
        self.entry_dZ.setSingleStep(1)
        self.entry_dZ.setValue(0)
        self.entry_vZ = QDoubleSpinBox()
        self.entry_vZ.setMinimum(0) 
        self.entry_vZ.setMaximum(100) 
        self.entry_vZ.setSingleStep(1)
        self.entry_vZ.setValue(5)
        self.entry_aZ = QDoubleSpinBox()
        self.entry_aZ.setMinimum(0) 
        self.entry_aZ.setMaximum(500) 
        self.entry_aZ.setSingleStep(1)
        self.entry_aZ.setValue(20)
        self.combo_ustepZ = QComboBox()
        self.combo_ustepZ.addItem('1')
        self.combo_ustepZ.addItem('2')
        self.combo_ustepZ.addItem('4')
        self.combo_ustepZ.addItem('8')
        self.combo_ustepZ.addItem('16')
        self.combo_ustepZ.addItem('32')
        self.combo_ustepZ.addItem('64')
        self.btn_moveZ_forward = QPushButton('Forward')
        self.btn_moveZ_forward.setDefault(False)
        self.btn_moveZ_backward = QPushButton('Backward')
        self.btn_moveZ_backward.setDefault(False)
        self.btn_cycleZ = QPushButton('Cycle')
        self.btn_cycleZ.setDefault(False)
        
        grid_line0 = QGridLayout()
        grid_line0.addWidget(QLabel('X (mm)'), 0,0)
        grid_line0.addWidget(self.label_Xpos, 0,1)
        grid_line0.addWidget(QLabel('d (mm)'), 0,2)
        grid_line0.addWidget(self.entry_dX, 0,3)
        grid_line0.addWidget(QLabel('v (mm/s)'), 0,4)
        grid_line0.addWidget(self.entry_vX, 0,5)
        grid_line0.addWidget(QLabel('a (mm/s/s)'), 0,6)
        grid_line0.addWidget(self.entry_aX, 0,7)
        grid_line0.addWidget(QLabel('ustepping'), 0,8)
        grid_line0.addWidget(self.combo_ustepX, 0,9)
        grid_line0.addWidget(self.btn_moveX_forward, 0,10)
        grid_line0.addWidget(self.btn_moveX_backward, 0,11)
        grid_line0.addWidget(self.btn_cycleX, 0,12)

        grid_line1 = QGridLayout()
        grid_line1.addWidget(QLabel('Y (mm)'), 0,0)
        grid_line1.addWidget(self.label_Ypos, 0,1)
        grid_line1.addWidget(QLabel('d (mm)'), 0,2)
        grid_line1.addWidget(self.entry_dY, 0,3)
        grid_line1.addWidget(QLabel('v (mm/s)'), 0,4)
        grid_line1.addWidget(self.entry_vY, 0,5)
        grid_line1.addWidget(QLabel('a (mm/s/s)'), 0,6)
        grid_line1.addWidget(self.entry_aY, 0,7)
        grid_line1.addWidget(QLabel('ustepping'), 0,8)
        grid_line1.addWidget(self.combo_ustepY, 0,9)
        grid_line1.addWidget(self.btn_moveY_forward, 0,10)
        grid_line1.addWidget(self.btn_moveY_backward, 0,11)
        grid_line1.addWidget(self.btn_cycleY, 0,12)

        grid_line2 = QGridLayout()
        grid_line2.addWidget(QLabel('Z (mm)'), 0,0)
        grid_line2.addWidget(self.label_Zpos, 0,1)
        grid_line2.addWidget(QLabel('d (mm)'), 0,2)
        grid_line2.addWidget(self.entry_dZ, 0,3)
        grid_line2.addWidget(QLabel('v (mm/s)'), 0,4)
        grid_line2.addWidget(self.entry_vZ, 0,5)
        grid_line2.addWidget(QLabel('a (mm/s/s)'), 0,6)
        grid_line2.addWidget(self.entry_aZ, 0,7)
        grid_line2.addWidget(QLabel('ustepping'), 0,8)
        grid_line2.addWidget(self.combo_ustepZ, 0,9)
        grid_line2.addWidget(self.btn_moveZ_forward, 0,10)
        grid_line2.addWidget(self.btn_moveZ_backward, 0,11)
        grid_line2.addWidget(self.btn_cycleZ, 0,12)

        self.grid = QGridLayout()
        self.grid.addLayout(grid_line0,0,0)
        self.grid.addLayout(grid_line1,1,0)
        self.grid.addLayout(grid_line2,2,0)
        self.setLayout(self.grid)

        self.btn_moveX_forward.clicked.connect(self.move_x_forward)
        self.btn_moveX_backward.clicked.connect(self.move_x_backward)
        self.btn_cycleX.clicked.connect(self.cycle_x)

        self.btn_moveY_forward.clicked.connect(self.move_y_forward)
        self.btn_moveY_backward.clicked.connect(self.move_y_backward)
        self.btn_cycleY.clicked.connect(self.cycle_y)
        
        self.btn_moveZ_forward.clicked.connect(self.move_z_forward)
        self.btn_moveZ_backward.clicked.connect(self.move_z_backward)
        self.btn_cycleZ.clicked.connect(self.cycle_z)
        
    def move_x_forward(self):
        self.navigationController.move_x(self.entry_dX.value(),self.entry_vX.value(),self.entry_aX.value(),int(self.combo_ustepX.currentText()))
    def move_x_backward(self):
        self.navigationController.move_x(-self.entry_dX.value(),self.entry_vX.value(),self.entry_aX.value(),int(self.combo_ustepX.currentText()))
    def move_y_forward(self):
        self.navigationController.move_y(self.entry_dY.value(),self.entry_vY.value(),self.entry_aY.value(),int(self.combo_ustepY.currentText()))
    def move_y_backward(self):
        self.navigationController.move_y(-self.entry_dY.value(),self.entry_vY.value(),self.entry_aY.value(),int(self.combo_ustepY.currentText()))
    def move_z_forward(self):
        self.navigationController.move_z(self.entry_dZ.value(),self.entry_vZ.value(),self.entry_aZ.value(),int(self.combo_ustepZ.currentText()))
    def move_z_backward(self):
        self.navigationController.move_z(-self.entry_dZ.value(),self.entry_vZ.value(),self.entry_aZ.value(),int(self.combo_ustepZ.currentText()))
    def cycle_x(self):
        self.navigationController.cycle_x(self.entry_dX.value(),self.entry_vX.value(),self.entry_aX.value(),int(self.combo_ustepX.currentText()))
    def cycle_y(self):
        self.navigationController.cycle_y(self.entry_dY.value(),self.entry_vY.value(),self.entry_aY.value(),int(self.combo_ustepY.currentText()))
    def cycle_z(self):
        self.navigationController.cycle_z(self.entry_dZ.value(),self.entry_vZ.value(),self.entry_aZ.value(),int(self.combo_ustepZ.currentText()))

